### ISSUE TITLE
Themes missing after installing plugin

### ISSUE THREAD

**Issue by St1ggy** [catppuccin/fleet#45] opened 2024-09-05 11:42 UTC
I have installed Catppuccin Fleet Theme, but I don't have any related themes in theme menu
<img width="600" alt="image" src="https://github.com/user-attachments/assets/3fd548f8-890c-4846-8fef-538a108998f9">
<img width="600" alt="image" src="https://github.com/user-attachments/assets/ae398040-d7ee-4058-98d8-c0f0efd2ad95">
<img width="600" alt="image" src="https://github.com/user-attachments/assets/46d151bb-de7a-4fab-ba4b-2426cc94d890">

I also don't have `.fleet` dir in my home folder
<img width="400" alt="image" src="https://github.com/user-attachments/assets/a05f1832-5236-423c-9996-6f8e646b48dd">

**Comment by sgoudham** [comment] 2024-09-05 11:49
Hey 👋,

That's quite odd 🤔 
Have you tried restarting Fleet since installing the plugin?

**Comment by shnypav** [comment] 2024-09-05 13:01
really weird one. Could you please try to remove the mentioning of the plugin from settings.json, approve the request in the app and then add it back? 
![ScreenShot Fleet settings json — distributed-calculator 2024-09-05 at 14 59 11](https://github.com/user-attachments/assets/f63a304e-62f0-4199-aff9-5d3918941fbe)

**Comment by shnypav** [comment] 2024-09-05 13:06
@St1ggy as for .fleet directory, now we store everything fleet related here `~/Library/Application\ Support/JetBrains/Fleet/` but anyway we do not add themes from plugins into the themes folder there

**Comment by shnypav** [comment] 2024-09-05 13:16
ok, could you please report an issue in our tracker? Please trigger the "Collect logs" action and attach the archive to the ticket. (Help -> Report Issue)

**Comment by St1ggy** [comment] 2024-09-05 13:26
> ok, could you please report an issue in our tracker? Please trigger the "Collect logs" action and attach the archive to the ticket. (Help -> Report Issue)

https://youtrack.jetbrains.com/issue/FL-29561/Cant-load-Catppuccin-Fleet-Theme-plugin
Done! Thank you!

**Comment by davfsa** [comment] 2024-09-05 15:04
> > @<mention> as for .fleet directory, now we store everything fleet related here ~/Library/Application\ Support/JetBrains/Fleet/ but anyway we do not add themes from plugins into the themes folder there

> I understand it, just noticed warning about ~/.fleet/theme/catppuccin-*.json in README.md

Yeah, sorry, that warning got outdated as of fleet 1.39, as they moved the theme folder to the new location, will update accordingly!

---

Unfortunately cannot reproduce the issue you mentioned, the plugin seems work properly and show all the available themes on my machine (Lenovo Thinkpad running Linux distro) so I presume it might be a bug with fleet on MacOS. Thanks @shnypav for taking a look at it so quickly!

**Comment by St1ggy** [comment] 2024-09-05 15:08
I will try to completely remove fleet from my computer, including the cache, and reinstall it. After that, I'll give the results here

**Comment by sgoudham** [comment] 2024-09-08 11:17
Just to confirm @St1ggy, are you still having trouble applying the theme in Fleet? It sounds like it was a problem on your end and not with the plugin.

I'll close this issue if you've got it working :+1:

**Comment by St1ggy** [comment] 2024-09-08 11:19
> Just to confirm @St1ggy, are you still having trouble applying the theme in Fleet? It sounds like it was a problem on your end and not with the plugin.
> 
> I'll close this issue if you've got it working 👍

Yep, thank you, you can close this issue. Sorry to bother you. :)

**Comment by sgoudham** [comment] 2024-09-08 11:23
No worries, thanks for the quick response!

**Closed by sgoudham** 2024-09-08 11:23 UTC
